#ifndef LUPINE_EMBEDDED_EMBEDDED_MAC_LIBRARIES_H_H
#define LUPINE_EMBEDDED_EMBEDDED_MAC_LIBRARIES_H_H

// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate_embedded_libraries.py --platform mac

#include <cstdint>
#include <unordered_map>
#include <vector>
#include <string>

namespace Lupine {

// Test library: test_lib (lib/libtest.a)
// Size: 8 bytes
// Checksum: test_checksum
const uint8_t embedded_mac_test_lib_data[] = {
    0xcf, 0xfa, 0xed, 0xfe, 0x07, 0x00, 0x00, 0x01,
};
const size_t embedded_mac_test_lib_data_size = 8;

/**
 * @brief Get map of embedded Mac libraries
 * @return Map of library name to data
 */
inline std::unordered_map<std::string, std::vector<uint8_t>> GetEmbeddedMacLibraries() {
    std::unordered_map<std::string, std::vector<uint8_t>> libraries;

    libraries["test_lib"] = std::vector<uint8_t>(
        embedded_mac_test_lib_data, embedded_mac_test_lib_data + embedded_mac_test_lib_data_size);

    return libraries;
}

} // namespace Lupine

#endif // LUPINE_EMBEDDED_EMBEDDED_MAC_LIBRARIES_H_H
