# Auto-generated CMake configuration for Lupine Engine
# Generated by setup_build_environment.py

# Platform detection
set(LUPINE_PLATFORM "WINDOWS")
set(LUPINE_ARCH "x64")
set(LUPINE_TRIPLET "x64-windows-static")

# Third-party paths
set(THIRDPARTY_DIR "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty")
set(PLATFORM_DIR "${THIRDPARTY_DIR}/Windows")

# Enable static linking
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib")

# Compiler flags for static linking
if(MSVC)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    add_compile_options(/Zc:__cplusplus /permissive- /W4)
else()
    add_compile_options(-Wall -Wextra -Wpedantic)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()

# Platform-specific configurations

# Windows-specific settings
set(VCPKG_DIR "${THIRDPARTY_DIR}/vcpkg")
# Note: CMAKE_TOOLCHAIN_FILE should be set via command line or before project() call
# This is just for reference and will be set by the build system
set(LUPINE_VCPKG_TOOLCHAIN_FILE "${VCPKG_DIR}/scripts/buildsystems/vcpkg.cmake")
if(EXISTS "${LUPINE_VCPKG_TOOLCHAIN_FILE}")
    set(VCPKG_TARGET_TRIPLET "${LUPINE_TRIPLET}")
    message(STATUS "vcpkg toolchain available: ${LUPINE_VCPKG_TOOLCHAIN_FILE}")
endif()

# Windows system libraries
set(WINDOWS_SYSTEM_LIBS
    user32 gdi32 shell32 advapi32 kernel32 ws2_32 opengl32
    dwmapi uxtheme winmm imm32 wtsapi32 setupapi version
    netapi32 userenv crypt32 secur32 bcrypt
)

# Qt configuration
set(QT_DIR "${THIRDPARTY_DIR}/Qt")
list(APPEND CMAKE_PREFIX_PATH "${QT_DIR}")

# Qt static linking setup
if(WIN32)
    set(QT_STATIC_DIR "${PLATFORM_DIR}/qtbase_x64-windows-static")
    if(EXISTS "${QT_STATIC_DIR}")
        set(Qt6_DIR "${QT_STATIC_DIR}/share/Qt6")
        list(APPEND CMAKE_PREFIX_PATH "${QT_STATIC_DIR}")
        add_compile_definitions(QT_STATIC_BUILD)
    endif()
endif()

# Emscripten configuration
set(EMSDK_DIR "${THIRDPARTY_DIR}/emsdk")
if(EXISTS "${EMSDK_DIR}")
    list(APPEND CMAKE_PREFIX_PATH "${EMSDK_DIR}")
endif()

# Library search paths
list(APPEND CMAKE_PREFIX_PATH "${PLATFORM_DIR}")

# Add all platform-specific package directories
if(EXISTS "${PLATFORM_DIR}")
    file(GLOB PLATFORM_PACKAGES "${PLATFORM_DIR}/*")
    foreach(package IN LISTS PLATFORM_PACKAGES)
        if(IS_DIRECTORY "${package}")
            list(APPEND CMAKE_PREFIX_PATH "${package}")
        endif()
    endforeach()
endif()

# Export functionality
option(LUPINE_ENABLE_EXPORT "Enable cross-platform export functionality" ON)
if(LUPINE_ENABLE_EXPORT)
    add_compile_definitions(
        LUPINE_EMBED_WINDOWS_LIBRARIES
        LUPINE_EMBED_LINUX_LIBRARIES
        LUPINE_EMBED_MACOS_LIBRARIES
        LUPINE_EMBED_ARM64_LIBRARIES
    )
endif()

# Debug information
message(STATUS "Lupine Platform: ${LUPINE_PLATFORM}")
message(STATUS "Lupine Architecture: ${LUPINE_ARCH}")
message(STATUS "Platform Directory: ${PLATFORM_DIR}")
message(STATUS "Third-party Directory: ${THIRDPARTY_DIR}")
